# Streamlit Cloud Secrets Configuration
# Add this in your Streamlit Cloud app settings under "Secrets"

# Google Gemini API Key (optional - can also be entered in the UI)
GEMINI_API_KEY = "AIzaSyDl60jKrQZ52WPppVhuRwOlFQF0HI0vcMk"

# Optional: Add other configuration
[settings]
default_confidence_threshold = 0.7
max_techniques_display = 5
